### ISSUE TITLE
"Not null violation" when updating DB

### ISSUE THREAD

**Issue by tehsquidge** [WedgeSama/array-field-type-extension#1]
Hi,

I was testing the extension and I came across a problem. I was trying to add:

```
...
        images:
            type: array
            children:
                image:
                    type: image
                    label: Image
                alt:
                    type: text
                    label: Alt Text
...
```

and, when updating/checking the DB, I got the error:

```
An exception occurred while executing 'ALTER TABLE bolt_pages ADD images TEXT NOT NULL': SQLSTATE[23502]: Not null violation: 7 ERROR: column "images" contains null values
```

I'm using:
- Bolt 2.2.3
- postgresql

Thanks!
